name: weather_app_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  custom_check_box: ^0.0.4
  equatable: ^2.0.3
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_screenutil: ^5.5.3+2
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  lottie: ^1.4.2
  percent_indicator: ^4.0.1
  pull_to_refresh_flutter3: ^2.0.1
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/forecast_icons/
    - assets/forecast_animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
    image: assets/app_splash_icon.png
    color: "#010101"
    android_gravity: center